server:
  port: 8084
fluent-bit:
  url: http://localhost:9880
  username: elastic
  password: 1016

spring:
  application:
    name: websocket-service
  security:
    user:
      name: btuser
      password: 1016
  datasource:
    url: jdbc:postgresql://localhost:5432/btrdb
    username: btuser
    password: 1016
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  redis:
    host: localhost
    port: 6379

